{% set name = "recon-para" %}
{% set version = "1.05.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/unavailable-2374/RECON/archive/refs/tags/v1.05-opt1.tar.gz
  sha256: d79dc8a0fb1797380fbf327c7a0d6e541411b9d5b8cbd7be6d8180674baacdae

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  run:
    - perl
    - coreutils

test:
  commands:
    - imagespread 2>&1 | grep -i "usage"

about:
  home: https://github.com/unavailable-2374/RECON
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: "Performance-optimized fork of RECON for de novo repeat family identification"
  description: |
    Performance-optimized fork of RECON v1.05, originally developed by
    Zhirong Bao and Sean Eddy (http://eddylab.org/software/recon/).
    Provides 10-50x speedup through algorithm fixes, I/O optimization,
    memory pool allocation, and parallel sorting.
  dev_url: https://github.com/unavailable-2374/RECON
  doc_url: http://eddylab.org/software/recon/

extra:
  identifiers:
    - doi:10.1101/gr.88502
  additional-platforms:
    - linux-aarch64
    - osx-arm64
